import { db } from '@/lib/db/prisma';
import { TOPIC_SEEDS } from '@/lib/youtube/topics';
import Link from 'next/link';

export default async function AdminTopicsPage() {
  // Count published videos per topic
  const topicCounts = await db.subjectTopic.groupBy({
    by: ['topicId'],
    _count: { _all: true },
  });

  const topicRecords = await db.topic.findMany({
    select: { id: true, slug: true, faqIntro: true },
  });

  const countMap = new Map(topicCounts.map((r) => [r.topicId, r._count._all]));
  const recordMap = new Map(topicRecords.map((r) => [r.slug, r]));

  return (
    <div className="max-w-4xl">
      <h1 className="mb-2 text-2xl font-bold text-gray-900">Topic Hubs</h1>
      <p className="mb-6 text-sm text-gray-500">
        All configured topic hubs. Video counts include all status levels. Click
        a topic to view its public hub page.
      </p>

      <div className="overflow-hidden rounded-xl border border-gray-200 bg-white">
        <table className="min-w-full divide-y divide-gray-200 text-sm">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-4 py-3 text-left font-medium text-gray-600">
                Topic
              </th>
              <th className="px-4 py-3 text-left font-medium text-gray-600">
                Slug
              </th>
              <th className="px-4 py-3 text-left font-medium text-gray-600">
                Risk
              </th>
              <th className="px-4 py-3 text-left font-medium text-gray-600">
                Videos
              </th>
              <th className="px-4 py-3 text-left font-medium text-gray-600">
                Has FAQ intro
              </th>
              <th className="px-4 py-3 text-left font-medium text-gray-600">
                Actions
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {TOPIC_SEEDS.map((t) => {
              const record = recordMap.get(t.slug);
              const count = record ? (countMap.get(record.id) ?? 0) : 0;
              return (
                <tr key={t.slug} className="hover:bg-gray-50">
                  <td className="px-4 py-3 font-medium text-gray-900">
                    {t.name}
                  </td>
                  <td className="px-4 py-3 text-gray-500">{t.slug}</td>
                  <td className="px-4 py-3">
                    {t.isHighRisk ? (
                      <span className="rounded-full bg-red-100 px-2 py-0.5 text-xs font-medium text-red-700">
                        High
                      </span>
                    ) : (
                      <span className="rounded-full bg-green-100 px-2 py-0.5 text-xs font-medium text-green-700">
                        Normal
                      </span>
                    )}
                  </td>
                  <td className="px-4 py-3 text-gray-600">{count}</td>
                  <td className="px-4 py-3">
                    {record?.faqIntro ? (
                      <span className="text-ink-muted/60 text-xs">✓ Yes</span>
                    ) : (
                      <span className="text-xs text-gray-400">—</span>
                    )}
                  </td>
                  <td className="px-4 py-3">
                    <Link
                      href={`/topics/${t.slug}`}
                      target="_blank"
                      className="text-ink text-xs hover:underline"
                    >
                      View hub →
                    </Link>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      <div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 px-5 py-4 text-sm text-amber-800">
        <strong>Note:</strong> Topic hubs are configured in{' '}
        <code className="rounded bg-amber-100 px-1 font-mono text-xs">
          lib/youtube/topics.ts
        </code>
        . To add or edit a topic, update that file. FAQ content is generated by
        the AI pipeline and stored in the database.
      </div>
    </div>
  );
}
